name: Cloud Functions

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cloud-functions.yml'
      - 'infrastructure/functions/**'

jobs:
  cloud-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Volta
        uses: volta-cli/action@v1

      - name: Install dependencies
        run: yarn cloud-functions:install

      - name: Build
        run: yarn cloud-functions:build

      - name: Install infrastructure tooling
        run: yarn infrastructure:install

      - name: Deploy
        run: yarn cloud-functions:deploy:ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
