name: Cloud Functions

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cloud-functions.yml'
      - 'infrastructure/functions/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x] # Only run the 10.x build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g firebase-tools yarn

      - name: Install dependencies
        run: yarn cloud-functions:install

      - name: Build
        run: yarn cloud-functions:build

      - name: Install infrastructure tooling
        run: yarn infrastructure:install

      - name: Deploy
        run: yarn cloud-functions:deploy:ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
