name: Build and Deploy CMS

on:
  push:
    branches:
      - master
    paths:
      - 'cms/**'
      - 'infrastructure/functions/**'
      - 'static-site-generator/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x] # Only run the 10.x build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn cms:install

      - name: Build
        run: ]yarn cms:build

      - name: Deploy
        run: yarn cms:deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
