name: CMS

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cms.yml'
      - 'cms/**'
      - 'infrastructure/functions/**'
      - 'static-site-generator/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup environment
        run: yarn setup:ci

      - name: Install dependencies
        run: yarn cms:install

      - name: Build
        run: yarn cms:build

      - name: Install infrastructure tooling
        run: yarn infrastructure:install

      - name: Deploy
        run: yarn cms:deploy:ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
