name: Static Site

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/static-site.yml'
      - 'content/**'
      - 'static-site-generator/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup environment
        run: yarn setup:ci

      - name: Install dependencies
        run: yarn static-site-generator:install

      - name: Build
        run: yarn static-site-generator:build

      - name: Install infrastructure tooling
        run: yarn infrastructure:install

      - name: Deploy
        run: yarn static-site-generator:deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
